const $=s=>document.querySelector(s);let csrf='',catalog=null,tab='products',editing=null;
const labels={products:'Artikel',drops:'Drops',offers:'Angebote'};const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);
async function api(path,options={}){const response=await fetch('/api/admin/'+path,{...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers}});let data;try{data=await response.json()}catch{throw new Error('Backend nicht erreichbar. Bitte die Cloudflare-Adresse verwenden.')}if(!response.ok){if(response.status===401&&path!=='login')loggedOut();throw new Error(data.error||'Anfrage fehlgeschlagen')}return data}
function notify(message){$('#notice').textContent=message}
function loggedOut(){$('#login').hidden=false;$('#dashboard').hidden=true;$('#logout').hidden=true;csrf='';catalog=null;$('#editor').close()}
async function load(){catalog=await api('catalog');$('#login').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;render()}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const values=Object.fromEntries(new FormData(e.target));const session=await api('login',{method:'POST',body:JSON.stringify(values)});csrf=session.csrf;e.target.password.value='';await load();notify('Angemeldet.')}catch(error){notify(error.message)}finally{button.disabled=false}});
$('#logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST',body:'{}'});loggedOut();notify('Abgemeldet.')}catch(e){notify(e.message)}});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',x===b));render()}));
function render(){$('#list-title').textContent=labels[tab];$('#stats').replaceChildren(...Object.keys(labels).map(key=>{const box=document.createElement('div');box.className='stat';const number=document.createElement('strong');number.textContent=catalog[key].length;const name=document.createElement('span');name.textContent=labels[key];box.append(number,name);return box}));$('#items').replaceChildren();if(!catalog[tab].length){const p=document.createElement('p');p.textContent='Noch keine Einträge. Erstelle deinen ersten Eintrag.';$('#items').append(p)}catalog[tab].forEach(item=>{const row=document.createElement('div');row.className='row';const info=document.createElement('div');const title=document.createElement('h3');title.textContent=item.name;const description=document.createElement('p');description.textContent=item.description;const status=document.createElement('small');status.textContent=(item.status==='published'?'Veröffentlicht':'Entwurf')+(tab==='products'?' · '+money(item.price):'')+(item.launchAt?' · Launch: '+new Date(item.launchAt).toLocaleString('de-DE'):'');info.append(title,description,status);const edit=document.createElement('button');edit.textContent='Bearbeiten';edit.addEventListener('click',()=>editor(item));const remove=document.createElement('button');remove.className='delete';remove.textContent='Entfernen';remove.addEventListener('click',()=>removeItem(item));row.append(info,edit,remove);$('#items').append(row)})}
function field(name,label,type,value='',options=[]){const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement(type==='textarea'?'textarea':type==='select'?'select':'input');el.name=name;if(type==='select'){options.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;el.append(o)})}else if(type!=='textarea')el.type=type;el.value=value;if(type==='number'){el.min='0';el.step=name==='percent'?'1':'0.01'}if(name==='name')el.required=true;wrap.append(el);return wrap}
function localDate(v){if(!v)return '';const date=new Date(v);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function editor(item=null){editing=item?structuredClone(item):null;$('#editor-title').textContent=labels[tab]+(item?' bearbeiten':' hinzufügen');$('#editor-error').textContent='';const fields=$('#fields');fields.replaceChildren(field('name','Name','text',item?.name||''),field('description','Text / Beschreibung','textarea',item?.description||''),field('status','Status','select',item?.status||'draft',[['draft','Entwurf'],['published','Veröffentlicht']]));
 if(tab==='products')fields.append(field('price','Preis (€)','number',item?item.price/100:''),field('images','Bildadressen (eine HTTPS-Adresse je Zeile)','textarea',item?.images.join('\n')||'/assets/front.webp'),field('sizes','Größen (mit Komma trennen)','text',item?.sizes.join(', ')||'XS, S, M, L, XL, XXL'),field('dropId','Drop','select',item?.dropId||'',[['','Kein Drop'],...catalog.drops.map(d=>[d.id,d.name])]));
 if(tab==='drops')fields.append(field('launchAt','Launch-Zeit (leer = sofort bei Veröffentlichung)','datetime-local',localDate(item?.launchAt)));
 if(tab==='offers'){fields.append(field('target','Artikel oder Drop','select',item?(item.productId?'product:'+item.productId:'drop:'+item.dropId):'',[['','Bitte auswählen'],...catalog.products.map(p=>['product:'+p.id,'Artikel: '+p.name]),...catalog.drops.map(d=>['drop:'+d.id,'Drop: '+d.name])]),field('kind','Angebotstyp','select',item?.kind||'percent',[['percent','Rabatt in Prozent'],['price','Aktionspreis in Euro']]),field('value','Wert (% oder € je nach Typ)','number',item?(item.kind==='price'?item.value/100:item.value):''),field('startAt','Beginn (optional)','datetime-local',localDate(item?.startAt)),field('endAt','Ende (optional)','datetime-local',localDate(item?.endAt)))}
 $('#editor').showModal()}
$('#add').addEventListener('click',()=>editor());$('#close-editor').addEventListener('click',()=>$('#editor').close());$('#cancel').addEventListener('click',()=>$('#editor').close());
async function save(next){try{catalog=await api('catalog',{method:'PUT',body:JSON.stringify(next)});render();notify('Gespeichert. Veröffentlichte Änderungen sind im Cloudflare-Shop sichtbar.')}catch(error){if(error.message.includes('inzwischen')){await load();notify('Ein anderer Stand wurde gespeichert. Bitte erneut bearbeiten.')}throw error}}
$('#editor-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const values=Object.fromEntries(new FormData(e.target));const date=v=>v?new Date(v).toISOString():'';let item={id:editing?.id||crypto.randomUUID(),name:values.name,description:values.description,status:values.status};if(tab==='products')item={...item,price:Math.round(Number(values.price)*100),images:values.images.split('\n').map(x=>x.trim()).filter(Boolean),sizes:values.sizes.split(',').map(x=>x.trim()).filter(Boolean),dropId:values.dropId};if(tab==='drops')item.launchAt=date(values.launchAt);if(tab==='offers'){const [type,id]=values.target.split(':');item={...item,productId:type==='product'?id:'',dropId:type==='drop'?id:'',kind:values.kind,value:values.kind==='price'?Math.round(Number(values.value)*100):Number(values.value),startAt:date(values.startAt),endAt:date(values.endAt)}}const next=structuredClone(catalog);if(editing)next[tab]=next[tab].map(x=>x.id===item.id?item:x);else next[tab].push(item);await save(next);$('#editor').close()}catch(error){$('#editor-error').textContent=error.message}finally{button.disabled=false}});
async function removeItem(item){if(!confirm(`„${item.name}“ entfernen? Verknüpfte Angebote werden ebenfalls entfernt. Artikel eines entfernten Drops werden zu Entwürfen.`))return;const next=structuredClone(catalog);next[tab]=next[tab].filter(x=>x.id!==item.id);if(tab==='products')next.offers=next.offers.filter(o=>o.productId!==item.id);if(tab==='drops'){next.products=next.products.map(p=>p.dropId===item.id?{...p,dropId:'',status:'draft'}:p);next.offers=next.offers.filter(o=>o.dropId!==item.id)}try{await save(next)}catch(error){notify(error.message)}}
(async()=>{try{const session=await api('session');csrf=session.csrf;await load()}catch(e){if(e.message!=='Bitte anmelden')notify(e.message)}})();
