const $=s=>document.querySelector(s);
const dialogs=[...document.querySelectorAll('dialog')];
function openDialog(id){dialogs.forEach(d=>d.close());$(id).showModal();document.body.classList.add('modal-open');}
dialogs.forEach(d=>{d.querySelectorAll('.close,.close-action').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('close',()=>{if(!dialogs.some(x=>x.open))document.body.classList.remove('modal-open')});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()})});
$('#year').textContent=new Date().getFullYear();
$('#menu-toggle').addEventListener('click',()=>{const expanded=$('#navigation').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',expanded);$('#menu-toggle').setAttribute('aria-label',expanded?'Close menu':'Open menu')});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false')}));
let selectedSize='M',activeProduct=null,products=[],drops=[];
let cart=[];try{const saved=JSON.parse(localStorage.getItem('aurion-bag')||'[]');if(Array.isArray(saved))cart=saved.filter(i=>typeof i.size==='string'&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=99).map(i=>({...i,id:i.id||'aurion-shirt'}))}catch{}
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);
function renderSizes(){$('.sizes').replaceChildren(...activeProduct.sizes.map(size=>{const b=document.createElement('button');b.type='button';b.textContent=size;b.setAttribute('aria-pressed',size===selectedSize);b.addEventListener('click',()=>{selectedSize=size;renderSizes()});return b}))}
function productOpen(p){activeProduct=p;selectedSize=p.sizes.includes('M')?'M':p.sizes[0];$('#product-dialog h2').textContent=p.name;$('#product-dialog .price').textContent=money(p.price)+(p.offerTitle?' · '+p.offerTitle:'');$('#product-dialog .product-info>.price+p').textContent=p.description;$('#product-image').src=p.images[0];$('#product-image').alt=p.name;$('.thumbnails').replaceChildren(...p.images.map((src,index)=>{const b=document.createElement('button');const img=document.createElement('img');img.src=src;img.alt=p.name+' — image '+(index+1);b.append(img);b.addEventListener('click',()=>{$('#product-image').src=src});return b}));$('#product-dialog .product-info details').hidden=p.id!=='aurion-shirt';$('#product-dialog .product-layout>div:first-child>h3').hidden=p.id!=='aurion-shirt';$('#product-dialog .product-layout>div:first-child>p').hidden=p.id!=='aurion-shirt';$('#product-status').textContent='';renderSizes();openDialog('#product-dialog')}
function saveCart(){try{localStorage.setItem('aurion-bag',JSON.stringify(cart))}catch{}renderCart()}
function renderCart(){$('#cart-count').textContent=cart.reduce((n,i)=>n+i.quantity,0);$('#cart-items').replaceChildren();if(!cart.length){const p=document.createElement('p');p.textContent='Your bag is empty. Discover the collection.';$('#cart-items').append(p)}cart.forEach(item=>{const product=products.find(p=>p.id===item.id);const row=document.createElement('div');row.className='cart-row';const img=document.createElement('img');img.src=product?.images[0]||'assets/front.webp';img.alt=product?.name||'Unavailable product';const p=document.createElement('p');p.textContent=product?`${product.name} · ${item.size} · Qty ${item.quantity} · ${money(item.quantity*product.price)}`:'This item is no longer available.';const b=document.createElement('button');b.textContent='Remove';b.setAttribute('aria-label',`Remove size ${item.size} from bag`);b.addEventListener('click',()=>{cart=cart.filter(i=>i!==item);saveCart()});row.append(img,p,b);$('#cart-items').append(row)});$('#cart-total').textContent=money(cart.reduce((n,i)=>n+i.quantity*(products.find(p=>p.id===i.id)?.price||0),0))}
$('#add-cart').addEventListener('click',()=>{if(!activeProduct)return;const item=cart.find(i=>i.size===selectedSize&&i.id===activeProduct.id);if(item){if(item.quantity>=99){$('#product-status').textContent='Maximum quantity reached.';return}item.quantity++}else cart.push({id:activeProduct.id,size:selectedSize,quantity:1});saveCart();$('#product-status').textContent=`Size ${selectedSize} added to your bag.`});
$('#cart-toggle').addEventListener('click',()=>{renderCart();openDialog('#cart-dialog')});
function renderCollection(){const section=$('#shop');section.replaceChildren();section.classList.add('catalog-section');const groups=[...drops];if(products.some(p=>!p.dropId))groups.push({id:'',name:'COLLECTION',description:''});if(!groups.length){const message=document.createElement('p');message.textContent='The next chapter is coming. New drops will appear here.';section.append(message)}for(const drop of groups){const wrap=document.createElement('div');wrap.className='catalog-drop';const intro=document.createElement('div');intro.className='drop-copy';const title=document.createElement('h2');title.textContent=drop.name;const desc=document.createElement('p');desc.textContent=drop.description;intro.append(title,desc);const grid=document.createElement('div');grid.className='catalog-grid';for(const p of products.filter(p=>p.dropId===drop.id)){const b=document.createElement('button');b.className='product-card';const img=document.createElement('img');img.src=p.images[0];img.alt=p.name;img.loading='lazy';const name=document.createElement('strong');name.textContent=p.name;const price=document.createElement('span');price.textContent=money(p.price);if(p.originalPrice>p.price){const original=document.createElement('del');original.textContent=money(p.originalPrice);price.prepend(original,' ')}const desc=document.createElement('p');desc.textContent=p.description;b.append(img,name,price,desc);if(p.offerTitle){const badge=document.createElement('small');badge.textContent=p.offerTitle;b.append(badge)}b.addEventListener('click',()=>productOpen(p));grid.append(b)}wrap.append(intro,grid);section.append(wrap)}renderCart()}
const preview={products:[{id:'aurion-shirt',name:'AURION T-SHIRT',description:'Oversized premium T-shirt crafted from 260 GSM pre-washed cotton. Finished with premium embroidery and HD screen print.',price:5990,originalPrice:5990,images:['assets/product.webp','assets/front.webp','assets/embroidery.webp'],sizes:['XS','S','M','L','XL','XXL'],dropId:'drop-001'}],drops:[{id:'drop-001',name:'DROP 001',description:'The first drop. Built on discipline. Driven by purpose. Made for those who earn everything.'}]};
async function loadCollection(){try{const response=await fetch('/api/public/catalog',{cache:'no-store'});if(!response.ok)throw new Error('Unavailable');const data=await response.json();if(!Array.isArray(data.products)||!Array.isArray(data.drops))throw new Error('Invalid catalog');products=data.products;drops=data.drops;renderCollection()}catch{if(location.hostname.endsWith('github.io')||['localhost','127.0.0.1'].includes(location.hostname)){products=preview.products;drops=preview.drops;renderCollection()}else{const p=document.createElement('p');p.textContent='The collection could not be loaded. Please reload the page.';$('#shop').replaceChildren(p)}}}
loadCollection();document.querySelectorAll('.product-open').forEach(b=>b.addEventListener('click',()=>{if(products[0])productOpen(products[0])}));
let lookIndex=0;function showLook(index){lookIndex=(index+4)%4;$('#lightbox-image').src=`assets/look-${lookIndex+1}.webp`;$('#lightbox-image').alt=document.querySelectorAll('.look img')[lookIndex].alt;$('#look-position').textContent=`${lookIndex+1} / 4`}
document.querySelectorAll('.look').forEach((b,i)=>b.addEventListener('click',()=>{showLook(i);openDialog('#image-dialog')}));$('#lookbook-all').addEventListener('click',()=>{showLook(0);openDialog('#image-dialog')});$('#previous-look').addEventListener('click',()=>showLook(lookIndex-1));$('#next-look').addEventListener('click',()=>showLook(lookIndex+1));$('#image-dialog').addEventListener('keydown',e=>{if(e.key==='ArrowLeft')showLook(lookIndex-1);if(e.key==='ArrowRight')showLook(lookIndex+1)});
$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();$('#newsletter-status').textContent='Newsletter registration opens with the launch. Your email has not been submitted or saved.'});
const info={shipping:['Shipping','Delivery regions, shipping costs and delivery times will be published before launch. Orders are not available yet.'],returns:['Returns','The returns policy and cancellation information will be available before checkout opens.'],faq:['FAQ','Drop 001 features an oversized cream T-shirt in XS–XXL, with 260 GSM cotton, premium embroidery and HD screen print. This website is currently a collection preview.'],imprint:['Imprint','The legal provider details must be added by the shop operator before commercial launch.'],privacy:['Privacy Policy','This preview stores your shopping bag in your browser’s local storage. Newsletter emails are not stored or transmitted. Fonts are loaded from Google Fonts. The complete privacy policy must be provided before launch.'],terms:['Terms & Conditions','Purchases are not currently possible. The operator must supply the applicable terms before enabling checkout.']};
document.querySelectorAll('.info-link').forEach(b=>b.addEventListener('click',()=>{const [title,content]=info[b.dataset.info];$('#info-title').textContent=title;$('#info-content').textContent=content;openDialog('#info-dialog')}));
$('#search-toggle').addEventListener('click',()=>{openDialog('#search-dialog');$('#search').focus();search()});
function search(){const term=$('#search').value.trim().toLowerCase();$('#search-results').replaceChildren();const matches=products.filter(p=>(p.name+' '+p.description+' '+(drops.find(d=>d.id===p.dropId)?.name||'')).toLowerCase().includes(term));if(matches.length){matches.forEach(p=>{const b=document.createElement('button');b.textContent=p.name+' — '+money(p.price);b.addEventListener('click',()=>productOpen(p));$('#search-results').append(b)})}else{const p=document.createElement('p');p.textContent='No products found.';$('#search-results').append(p)}}$('#search').addEventListener('input',search);
