const $=s=>document.querySelector(s);
const dialogs=[...document.querySelectorAll('dialog')];
function openDialog(id){dialogs.forEach(d=>d.close());$(id).showModal();document.body.classList.add('modal-open');}
dialogs.forEach(d=>{d.querySelectorAll('.close,.close-action').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('close',()=>{if(!dialogs.some(x=>x.open))document.body.classList.remove('modal-open')});d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()})});
$('#year').textContent=new Date().getFullYear();
$('#menu-toggle').addEventListener('click',()=>{const expanded=$('#navigation').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',expanded);$('#menu-toggle').setAttribute('aria-label',expanded?'Close menu':'Open menu')});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>{$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false')}));
let selectedSize='M';
const sizes=['XS','S','M','L','XL','XXL'];
function renderSizes(){$('.sizes').replaceChildren(...sizes.map(size=>{const b=document.createElement('button');b.type='button';b.textContent=size;b.setAttribute('aria-pressed',size===selectedSize);b.addEventListener('click',()=>{selectedSize=size;renderSizes()});return b}))}renderSizes();
document.querySelectorAll('.product-open').forEach(b=>b.addEventListener('click',()=>{$('#product-status').textContent='';openDialog('#product-dialog')}));
document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{$('#product-image').src=`assets/${b.dataset.image}.webp`;$('#product-image').alt=b.querySelector('img').alt}));
let cart=[];try{const saved=JSON.parse(localStorage.getItem('aurion-bag')||'[]');if(Array.isArray(saved))cart=saved.filter(i=>sizes.includes(i.size)&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=99)}catch{}
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);
function saveCart(){try{localStorage.setItem('aurion-bag',JSON.stringify(cart))}catch{}renderCart()}
function renderCart(){$('#cart-count').textContent=cart.reduce((n,i)=>n+i.quantity,0);$('#cart-items').replaceChildren();if(!cart.length){const p=document.createElement('p');p.textContent='Your bag is empty. Discover Drop 001.';$('#cart-items').append(p)}cart.forEach(item=>{const row=document.createElement('div');row.className='cart-row';const img=document.createElement('img');img.src='assets/front.webp';img.alt='Aurion T-shirt';const p=document.createElement('p');p.textContent=`AURION T-SHIRT · ${item.size} · Qty ${item.quantity} · ${money(item.quantity*59.9)}`;const b=document.createElement('button');b.textContent='Remove';b.setAttribute('aria-label',`Remove size ${item.size} from bag`);b.addEventListener('click',()=>{cart=cart.filter(i=>i.size!==item.size);saveCart()});row.append(img,p,b);$('#cart-items').append(row)});$('#cart-total').textContent=money(cart.reduce((n,i)=>n+i.quantity*59.9,0))}renderCart();
$('#add-cart').addEventListener('click',()=>{const item=cart.find(i=>i.size===selectedSize);if(item){if(item.quantity>=99){$('#product-status').textContent='Maximum quantity reached.';return}item.quantity++}else cart.push({size:selectedSize,quantity:1});saveCart();$('#product-status').textContent=`Size ${selectedSize} added to your bag.`});
$('#cart-toggle').addEventListener('click',()=>openDialog('#cart-dialog'));
let lookIndex=0;function showLook(index){lookIndex=(index+4)%4;$('#lightbox-image').src=`assets/look-${lookIndex+1}.webp`;$('#lightbox-image').alt=document.querySelectorAll('.look img')[lookIndex].alt;$('#look-position').textContent=`${lookIndex+1} / 4`}
document.querySelectorAll('.look').forEach((b,i)=>b.addEventListener('click',()=>{showLook(i);openDialog('#image-dialog')}));$('#lookbook-all').addEventListener('click',()=>{showLook(0);openDialog('#image-dialog')});$('#previous-look').addEventListener('click',()=>showLook(lookIndex-1));$('#next-look').addEventListener('click',()=>showLook(lookIndex+1));$('#image-dialog').addEventListener('keydown',e=>{if(e.key==='ArrowLeft')showLook(lookIndex-1);if(e.key==='ArrowRight')showLook(lookIndex+1)});
$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();$('#newsletter-status').textContent='Newsletter registration opens with the launch. Your email has not been submitted or saved.'});
const info={shipping:['Shipping','Delivery regions, shipping costs and delivery times will be published before launch. Orders are not available yet.'],returns:['Returns','The returns policy and cancellation information will be available before checkout opens.'],faq:['FAQ','Drop 001 features an oversized cream T-shirt in XS–XXL, with 260 GSM cotton, premium embroidery and HD screen print. This website is currently a collection preview.'],imprint:['Imprint','The legal provider details must be added by the shop operator before commercial launch.'],privacy:['Privacy Policy','This preview stores your shopping bag in your browser’s local storage. Newsletter emails are not stored or transmitted. Fonts are loaded from Google Fonts. The complete privacy policy must be provided before launch.'],terms:['Terms & Conditions','Purchases are not currently possible. The operator must supply the applicable terms before enabling checkout.']};
document.querySelectorAll('.info-link').forEach(b=>b.addEventListener('click',()=>{const [title,content]=info[b.dataset.info];$('#info-title').textContent=title;$('#info-content').textContent=content;openDialog('#info-dialog')}));
$('#search-toggle').addEventListener('click',()=>{openDialog('#search-dialog');$('#search').focus();search()});
function search(){const term=$('#search').value.trim().toLowerCase();$('#search-results').replaceChildren();if(!term||['aurion','t-shirt','shirt','drop 001','cotton','cream'].some(x=>x.includes(term))){const b=document.createElement('button');b.textContent='AURION T-SHIRT / DROP 001 — €59,90';b.addEventListener('click',()=>openDialog('#product-dialog'));$('#search-results').append(b)}else{const p=document.createElement('p');p.textContent='No products found.';$('#search-results').append(p)}}$('#search').addEventListener('input',search);
