import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import {seed,validateCatalog,publicCatalog} from '../server/catalog.js';import {AurionStore} from '../server/worker.js';
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});const copy=()=>structuredClone(seed);
test('Draft and scheduled drops hide products',()=>{const c=copy();c.drops[0].status='draft';assert.equal(publicCatalog(c).products.length,0);c.drops[0].status='published';c.drops[0].launchAt='2030-01-01T00:00:00Z';assert.equal(publicCatalog(c,0).products.length,0);assert.equal(publicCatalog(c,Date.parse('2031-01-01')).products.length,1)});
test('Offers respect target, status and dates',()=>{const c=copy();c.offers=[{id:'offer',name:'Launch',description:'',productId:'aurion-shirt',dropId:'',kind:'percent',value:20,status:'published',startAt:'2026-10-01T00:00:00Z',endAt:'2026-10-10T00:00:00Z'}];assert.equal(publicCatalog(c,Date.parse('2026-10-08')).products[0].price,4792);assert.equal(publicCatalog(c,Date.parse('2026-10-11')).products[0].price,5990);c.offers[0].status='draft';assert.equal(publicCatalog(c,Date.parse('2026-10-08')).products[0].price,5990)});
test('Validate catalog input and reject unsafe images',()=>{for(const mutate of [c=>c.products[0].images=['javascript:alert(1)'],c=>c.products[0].images=['/assets/../admin.js'],c=>c.products[0].dropId='missing',c=>c.products[0].price=-1,c=>c.products[0].id=c.drops[0].id]){const c=copy();mutate(c);assert.throws(()=>validateCatalog(c))}assert.deepEqual(validateCatalog(copy()),copy())});
function store(){const map=new Map();const s={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),delete:async k=>map.delete(k),list:async({prefix})=>new Map([...map].filter(([k])=>k.startsWith(prefix))),setAlarm:async()=>{}};s.transaction=async fn=>fn(s);return s}
const sha=async v=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))).toString('hex');
function req(path,method='GET',body=null,headers={}){return new Request('https://aurion.test/api/'+path,{method,headers:{Origin:'https://aurion.test','Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})})}
test('Admin closed without secret, public catalog available',async()=>{const w=new AurionStore({storage:store()},{});assert.equal((await w.fetch(req('admin/session'))).status,503);assert.equal((await w.fetch(req('public/catalog'))).status,200)});
test('Secure login, CSRF, optimistic locking, rotation and logout',async()=>{const password='long-test-password-1234';const env={ADMIN_PASSWORD_HASH:await sha(password)};const w=new AurionStore({storage:store()},env);assert.equal((await w.fetch(req('admin/catalog'))).status,401);assert.equal((await w.fetch(req('admin/login','POST',{username:'admin',password},{Origin:'https://evil.test'}))).status,403);const r=await w.fetch(req('admin/login','POST',{username:'admin',password}));assert.equal(r.status,200);const cookie=r.headers.get('Set-Cookie');for(const flag of ['HttpOnly','Secure','SameSite=Strict'])assert.ok(cookie.includes(flag));const {csrf}=await r.json();const headers={Cookie:cookie.split(';')[0],'X-CSRF-Token':csrf};assert.equal((await w.fetch(req('admin/session','GET',null,headers))).status,200);assert.equal((await w.fetch(req('admin/catalog','PUT',copy(),{Cookie:headers.Cookie}))).status,403);assert.equal((await w.fetch(req('admin/catalog','PUT',copy(),headers))).status,200);assert.equal((await w.fetch(req('admin/catalog','PUT',copy(),headers))).status,409);env.ADMIN_PASSWORD_HASH=await sha('another-password-1234');assert.equal((await w.fetch(req('admin/session','GET',null,headers))).status,401);env.ADMIN_PASSWORD_HASH=await sha(password);assert.equal((await w.fetch(req('admin/logout','POST',{},headers))).status,200);assert.equal((await w.fetch(req('admin/session','GET',null,headers))).status,401)});
test('Rate limit blocks repeated guessing',async()=>{const w=new AurionStore({storage:store()},{ADMIN_PASSWORD_HASH:await sha('password-123456789')});for(let i=0;i<5;i++)assert.equal((await w.fetch(req('admin/login','POST',{username:'admin',password:'wrong'}))).status,401);assert.equal((await w.fetch(req('admin/login','POST',{username:'admin',password:'wrong'}))).status,429)});
